SQL:
    IP: localhost
    Port: 3306
    Database: mc
    User: root
    Password: 000000
Setting:
    Union:
        #1级公会设定
        '1':
            MaxMembers: 10
            MaxBank: 10000
            